### ISSUE TITLE
Mage registry key "_resource_singleton/ewcore/config_data" already exists

### ISSUE THREAD

**Issue by thenerdsinn** [magento-hackathon/Magento-PSR-0-Autoloader#12]
Hi, thanks for this awesome module, it solved autoloader problem but is causing 
"Mage registry key "_resource_singleton/ewcore/config_data" already exists " after every cache clear. can you please guide me in the right direction.
`Mage registry key "_resource_singleton/ewcore/config_data" already exists

Trace:
#0 /var/www/magento/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /var/www/magento/app/Mage.php(519): Mage::register('_resource_singl...', false)
#2 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(139): Mage::getResourceSingleton('ewcore/config_d...')
#3 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Abstract.php(45) : eval()'d code(45): Mage_Core_Model_Abstract->_getResource()
#4 [internal function]: ExtendwareInternal_EWCore_Model_Mage_Core_Abstract->_1i79otf(Array)
#5 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Abstract.php(45) : eval()'d code(45): call_user_func_array(Array, Array)
#6 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): ExtendwareInternal_EWCore_Model_Mage_Core_Abstract->__call('loadByData', Array)
#7 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): Extendware_EWCore_Model_Config_Data->loadByData(Array)
#8 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_Serial::getFromDatabase('Extendware_EWCo...')
#9 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_Serial::getValue('Extendware_EWCo...')
#10 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/License.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_Serial::factory('Extendware_EWCo...')
#11 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/License.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_License::getSerialFor('Extendware_EWCo...')
#12 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Mysql4/Abstract.php(29) : eval()'d code(1) : eval()'d code(1) : eval()'d code(31): Extendware_EWCore_Model_Module_License::factory('Extendware_EWCo...')
#13 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Mysql4/Abstract.php(29) : eval()'d code(1) : eval()'d code(1): eval()
#14 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Mysql4/Abstract.php(29) : eval()'d code(1): eval()
#15 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Mysql4/Abstract.php(29): eval()
#16 /var/www/magento/app/code/community/Hackathon/PSR0Autoloader/Model/SplAutoloader.php(152): include_once('/var/www/magent...')
#17 [internal function]: Hackathon_PSR0Autoloader_Model_SplAutoloader->loadClass('Extendware_EWCo...')
#18 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mysql4/Config/Data.php(4) : eval()'d code(1) : eval()'d code(1) : eval()'d code(2): spl_autoload_call('Extendware_EWCo...')
#19 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mysql4/Config/Data.php(4) : eval()'d code(1) : eval()'d code(1): eval()
#20 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mysql4/Config/Data.php(4) : eval()'d code(1): eval()
#21 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mysql4/Config/Data.php(4): eval()
#22 /var/www/magento/app/code/community/Hackathon/PSR0Autoloader/Model/SplAutoloader.php(152): include_once('/var/www/magent...')
#23 [internal function]: Hackathon_PSR0Autoloader_Model_SplAutoloader->loadClass('Extendware_EWCo...')
#24 [internal function]: spl_autoload_call('Extendware_EWCo...')
#25 /var/www/magento/app/code/local/Mage/Core/Model/Config.php(1366): class_exists('Extendware_EWCo...')
#26 /var/www/magento/app/code/local/Mage/Core/Model/Config.php(1400): Mage_Core_Model_Config->getModelInstance('ewcore_mysql4/c...', Array)
#27 /var/www/magento/app/Mage.php(491): Mage_Core_Model_Config->getResourceModelInstance('ewcore/config_d...', Array)
#28 /var/www/magento/app/Mage.php(519): Mage::getResourceModel('ewcore/config_d...', Array)
#29 /var/www/magento/app/code/core/Mage/Core/Model/Abstract.php(139): Mage::getResourceSingleton('ewcore/config_d...')
#30 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Abstract.php(45) : eval()'d code(45): Mage_Core_Model_Abstract->_getResource()
#31 [internal function]: ExtendwareInternal_EWCore_Model_Mage_Core_Abstract->_1i79otf(Array)
#32 /var/www/magento/app/code/local/Extendware/EWCore/Model/Mage/Core/Abstract.php(45) : eval()'d code(45): call_user_func_array(Array, Array)
#33 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): ExtendwareInternal_EWCore_Model_Mage_Core_Abstract->__call('loadByData', Array)
#34 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): Extendware_EWCore_Model_Config_Data->loadByData(Array)
#35 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_Serial::getFromDatabase('Extendware_EWPG...')
#36 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/Serial.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_Serial::getValue('Extendware_EWPG...')
#37 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/License.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_Serial::factory('Extendware_EWPG...')
#38 /var/www/magento/app/code/local/Extendware/EWCore/Model/Module/License.php(4) : eval()'d code(2): Extendware_EWCore_Model_Module_License::getSerialFor('Extendware_EWPG...')
#39 /var/www/magento/app/code/local/Extendware/EWPGrid/Helper/Data.php(41) : eval()'d code(1) : eval()'d code(1) : eval()'d code(43): Extendware_EWCore_Model_Module_License::factory('Extendware_EWPG...')
#40 /var/www/magento/app/code/local/Extendware/EWPGrid/Helper/Data.php(41) : eval()'d code(1) : eval()'d code(1): eval()
#41 /var/www/magento/app/code/local/Extendware/EWPGrid/Helper/Data.php(41) : eval()'d code(1): eval()
#42 /var/www/magento/app/code/local/Extendware/EWPGrid/Helper/Data.php(41): eval()
#43 /var/www/magento/app/code/community/Hackathon/PSR0Autoloader/Model/SplAutoloader.php(152): include_once('/var/www/magent...')
#44 [internal function]: Hackathon_PSR0Autoloader_Model_SplAutoloader->loadClass('Extendware_EWPG...')
#45 /var/www/magento/app/Mage.php(547): spl_autoload_call('Extendware_EWPG...')
#46 /var/www/magento/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(325): Mage::helper('ewpgrid')
#47 /var/www/magento/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(144): Mage_Adminhtml_Block_Page_Menu->_isEnabledModuleOutput(Object(Varien_Simplexml_Element))
#48 /var/www/magento/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(171): Mage_Adminhtml_Block_Page_Menu->_buildMenuArray(Object(Varien_Simplexml_Element), 'ewcore/quickacc...', 2)
#49 /var/www/magento/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(171): Mage_Adminhtml_Block_Page_Menu->_buildMenuArray(Object(Varien_Simplexml_Element), 'ewcore/', 1)
#50 /var/www/magento/app/code/core/Mage/Adminhtml/Block/Page/Menu.php(98): Mage_Adminhtml_Block_Page_Menu->_buildMenuArray()
#51 /var/www/magento/app/design/adminhtml/default/default/template/page/menu.phtml(30): Mage_Adminhtml_Block_Page_Menu->getMenuArray()
#52 /var/www/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/magent...')
#53 /var/www/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#54 /var/www/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#55 /var/www/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#56 /var/www/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#57 /var/www/magento/app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#58 /var/www/magento/app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('menu', true)
#59 /var/www/magento/app/design/adminhtml/default/default/template/page.phtml(53): Mage_Core_Block_Abstract->getChildHtml('menu')
#60 /var/www/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/var/www/magent...')
#61 /var/www/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#62 /var/www/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#63 /var/www/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#64 /var/www/magento/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#65 /var/www/magento/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#66 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#67 /var/www/magento/app/code/core/Mage/Adminhtml/controllers/System/AccountController.php(44): Mage_Core_Controller_Varien_Action->renderLayout()
#68 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_System_AccountController->indexAction()
#69 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#70 /var/www/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#71 /var/www/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#72 /var/www/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#73 /var/www/magento/index.php(100): Mage::run('', 'store')
#74 {main}`

**Comment by snowcore** [comment]
@thenerdsinn you can contact Extendware to fix this issue.

**Comment by CajuCLC** [comment]
Was anyone able to find a solution for this?
